### ISSUE TITLE
how to auto request every 15 minutes and get message error when redirect login page?

### ISSUE THREAD

**Issue by gumpon** [juliomotol/laravel-auth-timeout#20]

**Comment by juliomotol** [comment]
> ### how to auto request every 15 minutes

This is more of a frontend concern.

I'm not sure if it should be a part of the package, but I made a new release [v2.2.1](https://github.com/juliomotol/laravel-auth-timeout/releases/tag/v2.2.1) which introduces facades, allowing you to do something like this.

### `route/web.php`

```php
// First, lets create a dummy route where we could check if the user has timed
// out. DON'T put a 'auth.timeout' middleware here. Registering one will cause
// timeout counter to reset. 
Route::get('/auth-timeout-checker', function () {
    // If the user is not yet timed out, we'll return true. Otherwise return 
    // some url to redirect to.
    if (AuthTimeout::check()) {
        return response()->json(true);
    } else {
        return response()->json(['redirect' => route('some/path'), 401]);
    }
});
```

### Somewhere in your `.js` files

```js
setInterval(() => {
    // Assuming you're using axios, we'll make an ajax call to the route we
    // created to check for authentication.
    axios.get('/auth-timeout-checker')
        // We only need to catch the error, no need for the `then` chain.
        .catch(error => {
            // Check if the reponse status is 401 (authentication error) and
            // the contents has `redirect`.
            if (
                error.response.status === 401 &&
                typeof error.response.data.redirect === 'string'
            ) {
                // Redirect to the given path.
                window.location.href = error.response.data.redirect;
            }
        });
}, 6000); // This will run every 1 min, feel free to tweak to your liking.
```

---

> ### get message error when redirect login page

What do you mean by this?

**Comment by gumpon** [comment]
I want to rendering message in login page when throw authentication exception. (please seem photo)


Thankyou for your support


[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by juliomotol** [comment]
I don't see any photo. But it I think I get what you intend to do. You can use `Session` for this.

In the `route/web.php`...
```php
...
if (AuthTimeout::check()) {
    return response()->json(true);
}else{
    Session::put('timeout_message', 'Sorry you have timed out');
    return response()->json(['redirect' => route('some/path'), 401]);
}
...
```

You may want want to do the same thing in the middleware. See [Redirection](https://github.com/juliomotol/laravel-auth-timeout#redirection).
```php
...
protected function redirectTo($request, $guard = null)
{
    Session::put('timeout_message', 'Sorry you have timed out');
    return route('some/path');
}
...
```

Then in your blade view...
```
{{ Session::pull(timeout_message) }}
```

**Comment by gumpon** [comment]
I try to request 15 minutes  but not work.
![error-1](https://user-images.githubusercontent.com/676859/95945111-facf7700-0e13-11eb-83f8-a50864d05ce2.jpg)
![error-2](https://user-images.githubusercontent.com/676859/95945106-f99e4a00-0e13-11eb-8635-e579ca571ee5.jpg)
![error-3](https://user-images.githubusercontent.com/676859/95945439-ac6ea800-0e14-11eb-8f40-932d47e5aba6.jpg)

**Comment by juliomotol** [comment]
My bad, it should be like this.
```php
// somewhere in the  '/auth-timeout-checker' route declaration...
...
}else{
    Session::put('timeout_message', 'Sorry you have timed out');
    return response()->json(['redirect' => route('some/path')], 401); // 401 should be the 2nd parameter here...
}
...
```
Also, don't apply the 'auth.timeout' middleware on the '/auth-timeout-checker' route.

**Comment by gumpon** [comment]
yes, it's work. thankyou
