### ISSUE TITLE
Issues with 3.X and php 8.1?

### ISSUE THREAD

**Issue by Etern8ty** [juliomotol/laravel-auth-timeout#24]
I am prepping our system to update to php 8 but on any of the 3.X branches i get the following error:
Could not parse '1654029635': Failed to parse time string (1654029635) at position 7 (6): Unexpected character

I do not have the issue if we go back to 2.2.1 but obviously that is not php 8 compatible so it is of limited use

**Comment by juliomotol** [comment]
Could you provide the full error log/details?

**Comment by Etern8ty** [comment]
Here is the requested dump. It is probably worth noting that There seams to be some window of reset that "clears" it until a timeout at about 30 minutes. 

`[2022-06-01 07:02:39] local.ERROR: Could not parse '1654091297': Failed to parse time string (1654091297) at position 8 (9): Unexpected character {"userId":"d4def797-b81b-11e9-b58b-0050569671b6","exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Could not parse '1654091297': Failed to parse time string (1654091297) at position 8 (9): Unexpected character at /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:190)
[stacktrace]
#0 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): Carbon\\Carbon::rawParse()
#1 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/juliomotol/laravel-auth-timeout/src/AuthTimeout.php(79): Carbon\\Carbon::parse()
#2 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/juliomotol/laravel-auth-timeout/src/Middleware/AuthTimeoutMiddleware.php(60): JulioMotol\\AuthTimeout\\AuthTimeout->check()
#3 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): JulioMotol\\AuthTimeout\\Middleware\\AuthTimeoutMiddleware->handle()
#4 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#5 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#6 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#8 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#10 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#12 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#14 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#15 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#17 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#19 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#21 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#22 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#23 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#24 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#25 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#26 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#28 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#29 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#32 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#34 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#36 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#38 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#40 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#41 /home/etern8ty/git_repos/SMUS/sds_laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#42 /home/etern8ty/git_repos/SMUS/sds_laravel/server.php(21): require_once('...')
#43 {main}

[previous exception] [object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Failed to parse time string (1654091297) at position 8 (9): Unexpected character at /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:89)
[stacktrace]
#0 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(185): Carbon\\Carbon->__construct()
#1 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): Carbon\\Carbon::rawParse()
#2 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/juliomotol/laravel-auth-timeout/src/AuthTimeout.php(79): Carbon\\Carbon::parse()
#3 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/juliomotol/laravel-auth-timeout/src/Middleware/AuthTimeoutMiddleware.php(60): JulioMotol\\AuthTimeout\\AuthTimeout->check()
#4 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): JulioMotol\\AuthTimeout\\Middleware\\AuthTimeoutMiddleware->handle()
#5 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#6 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#7 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#9 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#11 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#13 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#15 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#16 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#18 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#20 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#22 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#24 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#26 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#30 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#32 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#33 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#35 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#37 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#39 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#41 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#42 /home/etern8ty/git_repos/SMUS/sds_laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#43 /home/etern8ty/git_repos/SMUS/sds_laravel/server.php(21): require_once('...')
#44 {main}

[previous exception] [object] (Exception(code: 0): Failed to parse time string (1654091297) at position 8 (9): Unexpected character at /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:87)
[stacktrace]
#0 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(87): DateTime->__construct()
#1 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(185): Carbon\\Carbon->__construct()
#2 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): Carbon\\Carbon::rawParse()
#3 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/juliomotol/laravel-auth-timeout/src/AuthTimeout.php(79): Carbon\\Carbon::parse()
#4 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/juliomotol/laravel-auth-timeout/src/Middleware/AuthTimeoutMiddleware.php(60): JulioMotol\\AuthTimeout\\AuthTimeout->check()
#5 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): JulioMotol\\AuthTimeout\\Middleware\\AuthTimeoutMiddleware->handle()
#6 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#8 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#10 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#12 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#14 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#16 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#17 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#19 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#21 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#23 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#24 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#25 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#26 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#27 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#28 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#30 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#31 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#33 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#34 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#36 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#38 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#40 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#42 /home/etern8ty/git_repos/SMUS/sds_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#43 /home/etern8ty/git_repos/SMUS/sds_laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#44 /home/etern8ty/git_repos/SMUS/sds_laravel/server.php(21): require_once('...')
#45 {main}
"} 
`

**Comment by Etern8ty** [comment]
Here is a dump of the session vars if its useful
`[2022-06-01 07:20:01] local.INFO: array (
  '_token' => '1KAJJdSEur5BnvZbuEozLWEGqmdLBPBOpOvWaNEz',
  'url' => 
  array (
  ),
  '_previous' => 
  array (
    'url' => 'http://127.0.0.1:8000/home',
  ),
  '_flash' => 
  array (
    'old' => 
    array (
    ),
    'new' => 
    array (
    ),
  ),
  'auth' => 
  array (
    'password_confirmed_at' => 1654090383,
  ),
  'login_smus_3dc7a913ef5fd4b890ecabe3487085573e16cf82' => 'd4daf797-5812-1119-be8b-0e5056ba71b6',
  'last_activity_time' => '1654091297',
)  `

**Comment by Etern8ty** [comment]
Issue seams to be that last_activity_time is a string. A horrible fix for the issue is add the following to  julimotol/laravel-auth-timeout/src/AuthTimeout.php:79
`
        if(ctype_digit(strval($this->session->get($this->session_name)))){
            $lastActiveAt = Carbon::parse((int)$this->session->get($this->session_name));   
        }else{
            $lastActiveAt = Carbon::parse($this->session->get($this->session_name));
        }
`

If one was using php 8 you could use is_numeric for less possible issues but seams to be a start. hope that helps find a real fix

**Comment by juliomotol** [comment]
Previously, on v2, we are basing the user's activity by getting the `time()` of the most recent request and storing that on the session. There may have been some parsing issue within the session since `time()` return an integer rather than a string.

Now in v3, [we're storing it as an ISO date time string](https://github.com/juliomotol/laravel-auth-timeout/blob/master/CHANGELOG.md#changed-1). You can try flushing the whole session.

But if that's not an option, I will release a compatibility fix for this. Might take me a couple of days since I haven't gotten my new machine fully setup yet.

**Comment by Etern8ty** [comment]
I am not sure I understand what you mean by clearing the whole session. If you mean the browser session or php session this happens on multiple machines with multiple OS's and multiple browsers. both laravel dev and deployed testing

Browsers: Chrome & Firefox
OS: Ubuntu 20.04, Mint 18.1

**Comment by juliomotol** [comment]
The PHP session, the method of doing so may vary depending on the session driver your using.

If you're using file driver (default), you can simply delete the `storage/sessions` directory.
If you're using database drive, you can truncate the `sessions` table.

**Comment by Etern8ty** [comment]
Well that sorta works so probably good?  we are using file on two machines and Memcached on the server in php 8 clearing the storage cache manually seams to work but on deploy server and in local testing with file and php7.4 it still seams not to work unfortunately

**Comment by juliomotol** [comment]
I've published a new release to resolve this issue. Please update to [v3.1.1](https://github.com/juliomotol/laravel-auth-timeout/releases/tag/v3.1.1).

If the issue still persist or anything comes up, let me know. Thanks!
