### ISSUE TITLE
"juliomotol/laravel-auth-timeout": "^4.0", is not working with Laravel 10

### ISSUE THREAD

**Issue by abacusintlere** [juliomotol/laravel-auth-timeout#29]
I have installed package and added its alias into kernal.php and put into the web.php and try to login it forcefully logout and redirecting back to login page even I changed the timeout to 15 mins but it is not permitting to logged into system, kindly guide me where is the issue.

**Comment by juliomotol** [comment]
Hi, could you share me the ff:

- have you been able to login without using the timeout middleware?
- can you show me where in your `web.php` you used the middleware alias?

**Comment by abacusintlere** [comment]
Hi, thanks for your response,

- Yeah When I removed auth.timeout middleware from my route then it works find and I can log into the system but if I places middleware then it redirect me to the login page.
- `Route::middleware(['auth', 'verified', 'first.change.password', 'user.status', 'auth.timeout'])->group(function(){
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
- }`

**Comment by juliomotol** [comment]
After further investigation, there was a erroneous condition on the timeout session initialization. I've published a [new release](https://github.com/juliomotol/laravel-auth-timeout/releases/tag/v4.0.1) for this. Update your dependency accordingly.

```bash
composer update juliomotol/laravel-auth-timeout
```

Let me know if the issue still persist
